### ISSUE TITLE
README.md sould include "grunt install" at end of Setup process

### ISSUE THREAD

**Issue by thomaspeugeot** [clientIO/joint#1304]
### Situation:
- follow setup instructions
```bash
cd joint
npm install

npm install -g grunt-cli 
grunt test
```
### Problem
- grunt fails

```
% grunt test 
Running "shell:rollup-test-bundle" (shell) task

wrappers/joint.wrapper.mjs → build/joint.nodeps.js...
created build/joint.nodeps.js in 1.4s

Running "mochaTest:server" (mochaTest) task
>> Mocha exploded!
>> Error: Cannot find module '../../build/joint'
>>   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
>>   at Function.Module._load (internal/modules/cjs/loader.js:562:25)
>>   at Module.require (internal/modules/cjs/loader.js:692:17)
...
```
### Proposed solution

- add the instruction before grunt test 
```bash
grunt install
```

**Comment by kumilingus** [comment]
Thanks @thomaspeugeot
