### ISSUE TITLE
Test React With Jest

### ISSUE THREAD

**Issue by ahmad2smile** [clientIO/joint#1475]
While switching from `jointjs` to `rappid@3.3.0`, Unable to run test on React with jest. While App is working fine,

Error:

```log
Test suite failed to run

    TypeError: Cannot read property 'prototype' of undefined

    >  7 | import { dia, shapes } from '@clientio/rappid';
         | ^

      at e (node_modules/@clientio/rappid/rappid.js:1:23792)
      at Object.<anonymous>.g (node_modules/@clientio/rappid/rappid.js:1:71)
      at Object.<anonymous> (node_modules/@clientio/rappid/rappid.js:1:4)
      at Object.<anonymous> (node_modules/@clientio/rappid/index.ts:1:1)
      ...(further app code stack)  
```

I previously on had to mock following `svg` API to make jest tests work as they were missing in JSDOM. https://gist.github.com/ahmad2smile/068e481d65b0cb82a7c9b9f1bc9d0ee0

I'm instlling rappid as:

```
"@clientio/rappid": "file:vendor/rappid.tgz",
```

Also had to do following jest fixes for other issues:

```
    "moduleNameMapper": {
      "\\.(css|less)$": "identity-obj-proxy"
    },
    "transformIgnorePatterns": [
      "node_modules/(?!@clientio)"
    ]
```

`envinfo`:

```
    Node: 12.22.1 - /usr/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.14.0 - /usr/bin/npm
```

<details>
   <summary>Attempt on Mocks</summary>

```typescript

  const mock = {
    // @ts-ignore
    prototype: {},
  };

  jest.spyOn(window, 'SVGPathSeg', 'get').mockImplementation(() => mock as never);
  jest.spyOn(window, 'SVGPathSegClosePath', 'get').mockImplementation(() => mock as never);
  jest.spyOn(window, 'SVGPathSegMovetoAbs', 'get').mockImplementation(() => mock as never);
  jest.spyOn(window, 'SVGPathSegMovetoRel', 'get').mockImplementation(() => mock as never);
  jest.spyOn(window, 'SVGPathSegLinetoAbs', 'get').mockImplementation(() => mock as never);
  jest.spyOn(window, 'SVGPathSegLinetoRel', 'get').mockImplementation(() => mock as never);
  jest.spyOn(window, 'SVGPathSegCurvetoCubicAbs', 'get').mockImplementation(() => mock as never);
  jest.spyOn(window, 'SVGPathSegCurvetoCubicRel', 'get').mockImplementation(() => mock as never);
  jest.spyOn(window, 'SVGPathSegCurvetoQuadraticAbs', 'get').mockImplementation(() => mock as never);
  jest.spyOn(window, 'SVGPathSegCurvetoQuadraticRel', 'get').mockImplementation(() => mock as never);
  jest.spyOn(window, 'SVGPathSegArcAbs', 'get').mockImplementation(() => mock as never);
  jest.spyOn(window, 'SVGPathSegArcRel', 'get').mockImplementation(() => mock as never);
  jest.spyOn(window, 'SVGPathSegLinetoHorizontalAbs', 'get').mockImplementation(() => mock as never);
  jest.spyOn(window, 'SVGPathSegLinetoHorizontalRel', 'get').mockImplementation(() => mock as never);
  jest.spyOn(window, 'SVGPathSegLinetoVerticalAbs', 'get').mockImplementation(() => mock as never);
  jest.spyOn(window, 'SVGPathSegLinetoVerticalRel', 'get').mockImplementation(() => mock as never);
  jest.spyOn(window, 'SVGPathSegCurvetoCubicSmoothAbs', 'get').mockImplementation(() => mock as never);
  jest.spyOn(window, 'SVGPathSegCurvetoCubicSmoothRel', 'get').mockImplementation(() => mock as never);
  jest.spyOn(window, 'SVGPathSegCurvetoQuadraticSmoothAbs', 'get').mockImplementation(() => mock as never);
  jest.spyOn(window, 'SVGPathSegCurvetoQuadraticSmoothRel', 'get').mockImplementation(() => mock as never);
  jest.spyOn(window, 'SVGPathElement', 'get').mockImplementation(() => mock as never);
  jest.spyOn(window, 'SVGPathSegList', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Property', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Point', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.RenderedElementBase', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.PathElementBase', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.svg', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.rect', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.circle', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.ellipse', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.line', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.polyline', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.polygon', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.path', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.pattern', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.marker', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.defs', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.GradientBase', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.linearGradient', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.radialGradient', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.stop', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.AnimateBase', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.animate', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.animateColor', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.animateTransform', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.font', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.fontface', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.missingglyph', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.glyph', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.text', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.TextElementBase', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.tspan', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.tref', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.a', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.image', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.g', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.symbol', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.style', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.use', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.mask', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.clipPath', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.filter', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.feDropShadow', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.feMorphology', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.feComposite', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.feColorMatrix', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.feGaussianBlur', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.title', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.desc', 'get').mockImplementation(() => mock as never);
  // @ts-ignore
  jest.spyOn(window, 'E.Element.MISSING', 'get').mockImplementation(() => mock as never);
  jest.spyOn(window, 'Element', 'get').mockImplementation(() => mock as never);
```
</details>

**Comment by jamesgeorgewilliams** [comment]
https://github.com/clientIO/rappid-tutorial-react/pull/3

This PR introduces a few updates from the default setup created by using create-react-app.

We needed to update the `test` script as apparently all config options are not available with the default setup of create-react-app.
It seems to have resolved similar issues mentioned here:
https://github.com/facebook/jest/issues/2550

We also added a mock `window.SVGPathElement = jest.fn();` which resolves the following error `TypeError: Cannot read property 'prototype' of undefined`.

**Comment by Anuthama-Ganesan** [comment]
I am trying to add a test with jest & enzyme for components using rappid.js. And I am encountering the same error `TypeError: Cannot read property 'prototype' of undefined.`
I have added the mock statement - `window.SVGPathElement = jest.fn();` and also added the code mentioned in setupTests.js as per the commit. 
node: v16.15.0
jest: 27.5.2,
Is there anything that I am missing?
