### ISSUE TITLE
Tests with jsdom error

### ISSUE THREAD

**Issue by dorsha** [clientIO/joint#520]
I'm using JointJS with ReactJS.

While running my tests, which use node+jsdom, I got the following error:

```
TypeError: e.createSVGMatrix is not a function
    at Function.d.createSVGMatrix (node_modules/rappid/build/rappid.min.js:54:12409)
    at b.extend.applyPortTransform (node_modules/rappid/build/rappid.min.js:58:1625)
    at .<anonymous> (node_modules/rappid/build/rappid.min.js:58:1372)
    at node_modules/rappid/node_modules/lodash/index.js:2874:23
    at node_modules/rappid/node_modules/lodash/index.js:3049:15
    at Function.<anonymous> (node_modules/rappid/node_modules/lodash/index.js:3346:13)
    at b.extend._layoutPorts (node_modules/rappid/build/rappid.min.js:58:1267)
    at .<anonymous> (node_modules/rappid/build/rappid.min.js:58:405)
    at node_modules/rappid/node_modules/lodash/index.js:2874:23
    at node_modules/rappid/node_modules/lodash/index.js:3073:15
    at baseForOwn (node_modules/rappid/node_modules/lodash/index.js:2046:14)
    at node_modules/rappid/node_modules/lodash/index.js:3043:18
    at Function.<anonymous> (node_modules/rappid/node_modules/lodash/index.js:3346:13)
    at b.extend._updatePorts (node_modules/rappid/build/rappid.min.js:58:285)
    at b.extend._renderPorts (node_modules/rappid/build/rappid.min.js:57:31846)
    at joint.dia.ElementView.joint.dia.CellView.extend.update (node_modules/rappid/build/rappid.min.js:56:13485)
    at wrapper [as update] (node_modules/rappid/node_modules/lodash/index.js:3095:19)
    at joint.dia.ElementView.joint.dia.CellView.extend.render (node_modules/rappid/build/rappid.min.js:56:15602)
    at a.render (node_modules/rappid/build/rappid.min.js:55:18076)
    at joint.dia.Paper.joint.mvc.View.extend.renderView (node_modules/rappid/build/rappid.min.js:57:18894)
    at node_modules/rappid/node_modules/lodash/index.js:2874:23
    at node_modules/rappid/node_modules/lodash/index.js:3049:15
    at Function.<anonymous> (node_modules/rappid/node_modules/lodash/index.js:3346:13)
    at joint.dia.Paper.joint.mvc.View.extend.resetViews (node_modules/rappid/build/rappid.min.js:57:19337)
    at triggerEvents (node_modules/rappid/node_modules/backbone/backbone.js:370:57)
    at triggerApi (node_modules/rappid/node_modules/backbone/backbone.js:356:19)
    at eventsApi (node_modules/rappid/node_modules/backbone/backbone.js:155:16)
    at Events.trigger (node_modules/rappid/node_modules/backbone/backbone.js:346:5)
    at triggerEvents (node_modules/rappid/node_modules/backbone/backbone.js:371:57)
    at triggerApi (node_modules/rappid/node_modules/backbone/backbone.js:357:22)
    at eventsApi (node_modules/rappid/node_modules/backbone/backbone.js:155:16)
    at Events.trigger (node_modules/rappid/node_modules/backbone/backbone.js:346:5)
    at _.extend.reset (node_modules/rappid/node_modules/backbone/backbone.js:952:33)
    at joint.dia.Graph.Backbone.Model.extend.resetCells (node_modules/rappid/build/rappid.min.js:55:22194)
    at .resetCells (node_modules/rappid/build/rappid.min.js:55:16547)
```

Seems that line 1137 returns an invalid element.
![image](https://cloud.githubusercontent.com/assets/5429033/23132257/aaa00698-f795-11e6-8a69-95cafc1587a1.png)

Did anyone encounter that? 
Is anyone using jsdom with jointjs?

**Comment by webmutation** [comment]
That looks like a JSDom issue (JSDOM does not support certain SVG APIs, so be aware of that). You should open an issue on their tracker and reference this one.

**Comment by danielpza** [comment]
@dorsha did you figure out a solution? Is there an issue on the jsdom tracker to follow?

**Comment by dorsha** [comment]
> @dorsha did you figure out a solution? Is there an issue on the jsdom tracker to follow?

I eventually used Selenium for those kind of tests,  it was long time ago, I think that you can work this out using Jest.

**Comment by jamesgeorgewilliams** [comment]
If using React with Jest/JSDom, it's possible to mock some of this functionality.

We have done this in our React tutorial (Created with create-react-app):
https://github.com/clientIO/rappid-tutorial-react

This PR introduces a fix for some the issues we faced:
https://github.com/clientIO/rappid-tutorial-react/pull/3
