### ISSUE TITLE
Unable to use DirectedLayout

### ISSUE THREAD

**Issue by AChakraborty1982** [clientIO/joint#584]
Getting this error in console.
[jointSample.zip](https://github.com/clientIO/joint/files/967857/jointSample.zip)

joint.min.js:56 Uncaught TypeError: Cannot read property 'Graph' of undefined(…)toGraphLib @ joint.min.js:56joint.dia.Graph.toGraphLib @ joint.min.js:56layout @ joint.min.js:56(anonymous function) @ callgraph2.js:27

**Comment by kumilingus** [comment]
Hi, you must include both the Dagre and Graphlib libraries as dependencies if you wish to use the layout.DirectedGraph plugin (http://resources.jointjs.com/docs/jointjs/v1.1/joint.html#layout.DirectedGraph).

**Comment by AChakraborty1982** [comment]
please see the html page, i have included them both.

**Comment by kumilingus** [comment]
![image](https://cloud.githubusercontent.com/assets/3967880/25586247/c567da2e-2e9e-11e7-8c1c-344a3452ca57.png)
Yeah, you are missing `dagre.min.js` and `graphlib.min.js`.

**Comment by AChakraborty1982** [comment]
![screenshot from 2017-05-01 18-54-15](https://cloud.githubusercontent.com/assets/26390759/25586459/b65a29a0-2e9f-11e7-9a22-9488fad934f3.png)


The screenshot you sent is commented out.

**Comment by kumilingus** [comment]
I see. The depencies (`dagre.min.js` and `graphlib.min.js`) have to be loaded before `joint.min.js`.

**Comment by denisemauldin** [comment]
So the latest version of graphlib (2.0.0) includes lodash 4.13.1, which then overwrites the lodash that's manually included.  You have to use graphlib 1.0.7.  `npm install graphlib@1.0.7 --save` 

After this there's an error where the "This is\nan element" fails with:

```
Uncaught DOMException: Failed to execute 'querySelector' on 'Element': '[model-id="This is
an element"]' is not a valid selector.
    at n.onEndModelChange (https://localhost:8443/static/libs/jointjs/joint.js:9091:45)
    at n.wrapper (https://localhost:8443/static/libs/lodash/index.js:3592:19)
    at n.watchEndModel [as watchSource] (https://localhost:8443/static/libs/jointjs/joint.js:9039:27)
    at n.render (https://localhost:8443/static/libs/jointjs/joint.js:8585:14)
    at n.protoProps.render (https://localhost:8443/static/libs/jointjs/joint.js:4699:26)
    at n.renderView (https://localhost:8443/static/libs/jointjs/joint.js:10603:14)
    at https://localhost:8443/static/libs/lodash/index.js:2874:23
    at https://localhost:8443/static/libs/lodash/index.js:3049:15
    at Function.<anonymous> (https://localhost:8443/static/libs/lodash/index.js:3346:13)
    at n.resetViews (https://localhost:8443/static/libs/jointjs/joint.js:10649:15)
```

If you remove that element then the graph renders fine.
