### ISSUE TITLE
JointJS typescript errors 

### ISSUE THREAD

**Issue by denisemauldin** [clientIO/joint#768]
Hi all,

I updated my node modules today and with TypeScript version 2.6.1 (and joint installed from github) I'm getting this error repeated every time JQuery is referenced with `node_modules/jointjs/dist/joint.d.ts`:
```
node_modules/jointjs/dist/joint.d.ts(1034,34): error TS2702: 'JQuery' only refers to a type, but is being used as a namespace here.
```

**Comment by vtalas** [comment]
Hi,

Are you able to run the `joint/demo/ts-demo` app? Is the error occurring there as well?

```
cd demo/ts-demo
npm install 
npm start
```

**Comment by denisemauldin** [comment]
```
node_modules/jointjs/demo/ts-demo > npm start

> @ start node_modules/jointjs/demo/ts-demo
> webpack

ts-loader: Using typescript@2.5.3 and node_modules/jointjs/demo/ts-demo/tsconfig.json
Hash: 6c7a1358a12afdf69f28
Version: webpack 3.7.1
Time: 3347ms
          Asset    Size  Chunks                    Chunk Names
build/bundle.js  274 kB       0  [emitted]  [big]  main
   [0] ./index.ts 1.37 kB {0} [built] [2 errors]
   [1] ./custom.ts 1.78 kB {0} [built] [2 errors]
    + 1 hidden module

ERROR in ./index.ts
(1,24): error TS2307: Cannot find module '../../build/joint'.

ERROR in ./index.ts
(3,20): error TS2307: Cannot find module '../../build/joint'.

ERROR in ./custom.ts
(1,24): error TS2307: Cannot find module '../../build/joint'.

ERROR in ./custom.ts
(4,16): error TS2664: Invalid module name in augmentation, module '../../build/joint' cannot be found.

ERROR in ./index.ts
Module not found: Error: Can't resolve '../../build/joint' in 'node_modules/jointjs/demo/ts-demo'
 @ ./index.ts 3:12-40 5:14-42

ERROR in ./custom.ts
Module not found: Error: Can't resolve '../../build/joint' in 'node_modules/jointjs/demo/ts-demo'
 @ ./custom.ts 13:12-40
 @ ./index.ts

npm ERR! Linux 3.10.0-514.10.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ start: `webpack`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ start script 'webpack'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     node_modules/jointjs/demo/ts-demo/npm-debug.log
```

cat npm-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.10
3 info using node@v6.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @~prestart: @
6 silly lifecycle @~prestart: no script for prestart, continuing
7 info lifecycle @~start: @
8 verbose lifecycle @~start: unsafe-perm in lifecycle true
9 verbose lifecycle @~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:node_modules/jointjs/demo/ts-demo/node_modules/.bin:/usr/local/lib/npm/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
10 verbose lifecycle @~start: CWD: node_modules/jointjs/demo/ts-demo
11 silly lifecycle @~start: Args: [ '-c', 'webpack' ]
12 silly lifecycle @~start: Returned: code: 2  signal: null
13 info lifecycle @~start: Failed to exec start script
14 verbose stack Error: @ start: `webpack`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid @
16 verbose cwd node_modules/jointjs/demo/ts-demo
17 error Linux 3.10.0-514.10.2.el7.x86_64
18 error argv "/usr/bin/node" "/usr/bin/npm" "start"
19 error node v6.10.0
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error @ start: `webpack`
22 error Exit status 2
23 error Failed at the @ start script 'webpack'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the  package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

There is a build directory created, but it is in the current directory (node_modules/jointjs/demo/ts-demo) and it only has the file `bundle.js` in it.

**Comment by vtalas** [comment]
you can run the `npm install & grunt` in the joint root, then go back and run the `npm start` again... This is not very pleasant indeed.

I've made a PR which simplify the process a little bit:
https://github.com/clientIO/joint/pull/770

It copies the `joint.d.ts, joint.js, joint.css` from the `dist` to the `demo/ts-demo/build` then you're able to work with the ts-demo without having the whole jointjs built.

**Comment by denisemauldin** [comment]
If I copy your PR and npm install, npm start (without doing npm install & grunt in the joint root) then I get:

```
node_modules/jointjs/demo/ts-demo (dev) > npm start

> @ start node_modules/jointjs/demo/ts-demo
> npm run build && live-server ./ --open=index.html --cors


> @ build node_modules/jointjs/demo/ts-demo
> npm run cp-libs & webpack


> @ cp-libs node_modules/jointjs/demo/ts-demo
> cpx ../../dist/joint.{d.ts,js,css} build


Usage: cpx <source> <dest> [options]

    Copy files, watching for changes.

        <source>  The glob of target files.
        <dest>    The path of a destination directory.

Options:

    -c, --command <command>   A command text to transform each file.
    -C, --clean               Clean files that matches <source> like pattern in
                              <dest> directory before the first copying.
    -L, --dereference         Follow symbolic links when copying from them.
    -h, --help                Print usage information.
    --include-empty-dirs      The flag to copy empty directories which is
                              matched with the glob.
    --no-initial              The flag to not copy at the initial time of watch.
                              Use together '--watch' option.
    -p, --preserve            The flag to copy attributes of files.
                              This attributes are uid, gid, atime, and mtime.
    -t, --transform <name>    A module name to transform each file. cpx lookups
                                the specified name via "require()".
    -u, --update              The flag to not overwrite files on destination if
                              the source file is older.
    -v, --verbose             Print copied/removed files.
    -V, --version             Print the version number.
    -w, --watch               Watch for files that matches <source>, and copy
                              the file to <dest> every changing.

Examples:

    cpx "src/**/*.{html,png,jpg}" app
    cpx "src/**/*.css" app --watch --verbose

See Also:
    https://github.com/mysticatea/cpx


npm ERR! Linux 3.10.0-514.10.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "cp-libs"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ cp-libs: `cpx ../../dist/joint.{d.ts,js,css} build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ cp-libs script 'cpx ../../dist/joint.{d.ts,js,css} build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cpx ../../dist/joint.{d.ts,js,css} build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!    node_modules/jointjs/demo/ts-demo/npm-debug.log
ts-loader: Using typescript@2.5.3 and node_modules/jointjs/demo/ts-demo/tsconfig.json
Hash: 6dd0a9e3274a0d512d42
Version: webpack 3.7.1
Time: 3598ms
          Asset    Size  Chunks                    Chunk Names
build/bundle.js  274 kB       0  [emitted]  [big]  main
   [0] ./index.ts 1.36 kB {0} [built] [2 errors]
   [1] ./custom.ts 1.78 kB {0} [built] [2 errors]
    + 1 hidden module

ERROR in ./index.ts
(1,24): error TS2307: Cannot find module './build/joint'.

ERROR in ./index.ts
(3,20): error TS2307: Cannot find module './build/joint'.

ERROR in ./custom.ts
(1,24): error TS2307: Cannot find module './build/joint'.

ERROR in ./custom.ts
(4,16): error TS2664: Invalid module name in augmentation, module './build/joint' cannot be found.

ERROR in ./index.ts
Module not found: Error: Can't resolve './build/joint' in 'node_modules/jointjs/demo/ts-demo'
 @ ./index.ts 3:12-36 5:14-38

ERROR in ./custom.ts
Module not found: Error: Can't resolve './build/joint' in 'node_modules/jointjs/demo/ts-demo'
 @ ./custom.ts 13:12-36
 @ ./index.ts

npm ERR! Linux 3.10.0-514.10.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ build: `npm run cp-libs & webpack`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ build script 'npm run cp-libs & webpack'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run cp-libs & webpack
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     node_modules/jointjs/demo/ts-demo/npm-debug.log

npm ERR! Linux 3.10.0-514.10.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ start: `npm run build && live-server ./ --open=index.html --cors`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script 'npm run build && live-server ./ --open=index.html --cors'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && live-server ./ --open=index.html --cors
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     node_modules/jointjs/demo/ts-demo/npm-debug.log
```


node_modules/jointjs/demo/ts-demo (dev) > ls ../../dist/joint*
```
../../dist/joint.core.css                     ../../dist/joint.min.js               ../../dist/joint.shapes.fsa.min.js
../../dist/joint.core.js                      ../../dist/joint.nowrap.js            ../../dist/joint.shapes.logic.js
../../dist/joint.core.min.css                 ../../dist/joint.nowrap.min.js        ../../dist/joint.shapes.logic.min.js
../../dist/joint.core.min.js                  ../../dist/joint.shapes.chess.js      ../../dist/joint.shapes.org.js
../../dist/joint.css                          ../../dist/joint.shapes.chess.min.js  ../../dist/joint.shapes.org.min.js
../../dist/joint.d.ts                         ../../dist/joint.shapes.devs.js       ../../dist/joint.shapes.pn.js
../../dist/joint.js                           ../../dist/joint.shapes.devs.min.js   ../../dist/joint.shapes.pn.min.js
../../dist/joint.layout.DirectedGraph.js      ../../dist/joint.shapes.erd.js        ../../dist/joint.shapes.uml.js
../../dist/joint.layout.DirectedGraph.min.js  ../../dist/joint.shapes.erd.min.js    ../../dist/joint.shapes.uml.min.js
../../dist/joint.min.css                      ../../dist/joint.shapes.fsa.js
```

**Comment by vtalas** [comment]
`cpx` is meant to be a cross-platform way how to copy files from the `dist` folder... hmmm

I've noticed the command should be wrapped in quotation marks :
 https://github.com/clientIO/joint/pull/770/commits/16cb99e5c829a0badee492e87678ce1dcc4e8532. 

I've tested it with the `npm v5.5.1`, on Windows and Ubuntu and surprisingly it worked well even without quotes.

**Comment by kumilingus** [comment]
Hi @denisemauldin, is this still an issue?

**Comment by denisemauldin** [comment]
We went back to the older version of jointjs.  As far as I know we're still getting the `node_modules/jointjs/dist/joint.d.ts(1034,34): error TS2702: 'JQuery' only refers to a type, but is being used as a namespace here.` error with our app,  but I'll see if I can find time to test again this week.

**Comment by Thunkar** [comment]
Hi, I'm also having this issue in a very similar scenario. Adding:

`import * as JQuery from "jquery";`

At the top of the node_modules/jointjs/dist/joint.d.ts file allows me to compile my code.

**Comment by Thunkar** [comment]
Ok, so that didn't work. Typescript exhibited a weird behavior and randomly failed compilation with the same error...

I had a workstation that never failed and made a diff with the failing computer's node_modules. The most obvious difference is that the module @types/jquery that the new one installed was a different version (1.10.34 vs 3.3.0). Forcing the installation of @types/jquery@3.3.0 solved the issue for me. Looks like backbone installed the older version, maybe the v3.3.0 should be forced by jointjs deps?

**Comment by Wildfirefox** [comment]
Hello everyone,
im facing the same error, since today. Is there any solution yet? Im using joint.js in version 2.0.1. I also tried to downgrade the version to version 2.0.0, but with no success. Maybe someone out there would like to share a proper solution?

**Comment by Thunkar** [comment]
@Wildfirefox try this:

`npm i --save-dev @types/jquery@3.3.0`

**Comment by Wildfirefox** [comment]
@Thunkar Ty for your fast response. I will test it today and give you a response then!

**Comment by Wildfirefox** [comment]
@Thunkar Your command worked very well for my project, thank you! 

BTW: Is there any guide to update from version 1.1 to 2.0.0 / 2.0.1? Im getting some others errors, regarding to JQuery.Events right now...

**Comment by kumilingus** [comment]
@Thunkar please see https://github.com/clientIO/joint/issues/937
